[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu.env]
CC = "aarch64-linux-gnu-gcc"
CXX = "aarch64-linux-gnu-g++"
CFLAGS = "-std=c99"

[target.s390x-unknown-linux-gnu]
linker = "s390x-linux-gnu-gcc"

[target.s390x-unknown-linux-gnu.env]
CC = "s390x-linux-gnu-gcc"
CXX = "s390x-linux-gnu-g++"
CFLAGS = "-std=c99"

# Also set for other Linux targets that might have issues
[target.x86_64-unknown-linux-gnu.env]
CFLAGS = "-std=c99"

[target.i686-unknown-linux-gnu.env]
CFLAGS = "-std=c99"


[target.powerpc64le-unknown-linux-gnu.env]
CFLAGS = "-std=c99"
